spring.application.name=leetcodeleaderboard
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.r2dbc.url=${DB_URL_R}
spring.r2dbc.username=${DB_USER}
spring.r2dbc.password=${DB_PASSWORD}
security.jwt.secret-key=${JWT_KEY}
# 1h in millisecond
security.jwt.expiration-time=${EXPIRATION_TIME}
spring.mail.host=${HOST}
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.config.import=optional:file:.env[.properties]